baseURL = "http://altinn.no/"
languageCode = "nb"
defaultContentLanguage = "nb"

contentDir = "content"
staticDir = "static"
publishDir = "public"

title = "Altinn"
theme = "hugo-theme-altinn"
metadataFormat = "yaml"
pluralizeListTitles = false
preservetaxonomynames = true
enableEmoji = true
enableGitInfo = false
disableKinds = ["RSS"] # page home section taxonomy taxonomyTerm RSS sitemap robotsTXT 404

[languages]
  [languages.nb]
    title = "Altinn"
    languageName = "Bokm√•l"
    weight = 1
  [languages.en]
    title = "Altinn"
    languageName = "English"
    weight = 2
  [languages.nn]
    title = "Altinn"
    languageName = "Nynorsk"
    weight = 3

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula"

[markup.tableOfContents]
startLevel = 2
endLevel = 2
ordered = false

[blackfriday]
fractions = false # disable automatic fraction rendering

[params]
editURL = "https://github.com/Altinn/altinn-infoportal/blob/main/content/"
noHomeIcon = true # default is false
noSearch = true # default is false
showVisitedLinks = false # default is false


[outputs]
home = ["HTML", "JSON"] # JSON generates index.json file used by search
